spring.application.name=indo
server.port=8080
spring.security.user.password=123456
spring.datasource.url=${CONNECTION_STRING}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
app.api.key=${OUTDOOR_API_KEY}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
# Stopping logging spam
# Disable startup info logs
spring.main.log-startup-info=false
# Logging levels
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN